# Generated by Django 3.1.7 on 2021-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('new_confirmed', models.IntegerField(max_length=30)),
                ('total_confirmed', models.IntegerField(max_length=30)),
                ('new_deaths', models.IntegerField(max_length=30)),
                ('total_deaths', models.IntegerField(max_length=30)),
                ('new_recovered', models.IntegerField(max_length=30)),
                ('total_recovered', models.IntegerField(max_length=30)),
            ],
        ),
    ]
