# Generated by Django 3.1.7 on 2021-12-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='new_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='new_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.IntegerField(default=0),
        ),
    ]
